version: "3"

networks:
  nw-admin:
    driver: bridge
  nw-api-admin:
    driver: bridge
  nw-lecturer:
    driver: bridge
  nw-api-lecturer:
    driver: bridge
  nw-student:
    driver: bridge
  nw-api-student:
    driver: bridge
  nw-redis:
    driver: bridge

services:
  nginx:
    build:
      context: ./nginx
    networks:
      - nw-redis
      - nw-admin
      - nw-api-admin
      - nw-lecturer
      - nw-api-lecturer
      - nw-student
      - nw-api-student
    hostname: nginx
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx
    depends_on:
      - redis
      - admin-service
      - admin-api-service
      - lecturer-service
      - lecturer-api-service
      - student-service
      - student-api-service

  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis.local
    networks:
      - nw-redis
    ports:
      - "6379:6379"
    command: redis-server --loglevel warning --requirepass "redis123"
    volumes:
      - ./redis/data:/data
    environment:
      FORCE_COLOR: 1
      DEBUG_COLORS: "true"
      TERM: xterm-256color
      COLORTERM: truecolor

  admin-service:
    build:
      context: ../clients/admin
    container_name: admin-service
    hostname: awa-classroom-admin.local
    networks:
      - nw-admin
      - nw-redis
    ports:
      - "3002:3002"
    environment:
      FORCE_COLOR: 1
      DEBUG_COLORS: "true"
      TERM: xterm-256color
      COLORTERM: truecolor
    depends_on:
      - redis

  admin-api-service:
    build:
      context: ../servers/admin
    container_name: admin-api-service
    hostname: awa-classroom-admin-api.local
    networks:
      - nw-api-admin
      - nw-redis
    ports:
      - "5002:5002"
    environment:
      FORCE_COLOR: 1
      DEBUG_COLORS: "true"
      TERM: xterm-256color
      COLORTERM: truecolor
    depends_on:
      - redis

  lecturer-service:
    build:
      context: ../clients/lecturer
    container_name: lecturer-service
    hostname: awa-classroom-lecturer.local
    networks:
      - nw-lecturer
      - nw-redis
    ports:
      - "3001:3001"
    environment:
      FORCE_COLOR: 1
      DEBUG_COLORS: "true"
      TERM: xterm-256color
      COLORTERM: truecolor
    depends_on:
      - redis

  lecturer-api-service:
    build:
      context: ../servers/lecturer
    container_name: lecturer-api-service
    hostname: awa-classroom-lecturer-api.local
    networks:
      - nw-api-lecturer
      - nw-redis
    ports:
      - "5001:5001"
    environment:
      FORCE_COLOR: 1
      DEBUG_COLORS: "true"
      TERM: xterm-256color
      COLORTERM: truecolor
    depends_on:
      - redis

  student-service:
    build:
      context: ../clients/student
    container_name: student-service
    hostname: awa-classroom-student.local
    networks:
      - nw-student
      - nw-redis
    ports:
      - "3000:3000"
    environment:
      FORCE_COLOR: 1
      DEBUG_COLORS: "true"
      TERM: xterm-256color
      COLORTERM: truecolor
    depends_on:
      - redis

  student-api-service:
    build:
      context: ../servers/student
    container_name: student-api-service
    hostname: awa-classroom-student-api.local
    networks:
      - nw-api-student
      - nw-redis
    ports:
      - "5000:5000"
    environment:
      FORCE_COLOR: 1
      DEBUG_COLORS: "true"
      TERM: xterm-256color
      COLORTERM: truecolor
    depends_on:
      - redis

  # zookeeper:
  #   image: 'zookeeper'
  #   restart: always
  #   hostname: zookeeper
  #   container_name: kabgo-zookeeper
  #   ports:
  #     - 2181:2181
  #   environment:
  #     - ALLOW_ANONYMOUS_LOGIN=yes
  #     - FORCE_COLOR=1
  #     - DEBUG_COLORS="true"
  #     - TERM=xterm-256color
  #     - COLORTERM=truecolor

  # kafka:
  #   image: 'bitnami/kafka'
  #   hostname: kafka.kabgo.local
  #   container_name: kabgo-kafka
  #   ports:
  #     - '9092:9092'
  #   environment:
  #     - KAFKA_CFG_BROKER_ID=1
  #     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - KAFKA_CFG_LISTENERS=PLAINTEXT://localhost:9092
  #     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
  #     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #     - KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND=true
  #     - FORCE_COLOR=1
  #     - DEBUG_COLORS="true"
  #     - TERM=xterm-256color
  #     - COLORTERM=truecolor
  #   depends_on:
  #     - zookeeper
